import type { Metadata } from "next";
import { getUserRole } from "@/lib/getUserRole";
export const metadata: Metadata = {
  title: "Not authorized",
  description: "Generated by create next app",
};

export default async function NotAuthorizedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  

  return <>{children}</>;
}
