
import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "../globals.css"
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "./(routes)/(root)/components";
import { Footer, NavBar } from "@/components/Shared";
import { Toaster } from "@/components/ui/sonner";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${spaceGrotesk.className} antialiased bg-white`}
      
      >
       <SidebarProvider>
        <AppSidebar></AppSidebar>
        <div className="w-full bg-stone-100 flex flex-col min-h-screen">
          <NavBar/>
        
            <main className="flex-1">
        {children} 
        </main>
        <Toaster></Toaster>
        <Footer></Footer>
        </div>
        </SidebarProvider> 
      </body>
    </html>
    </ClerkProvider>
  );
}
